version: '3.8'

services:
  anaconda:
    build: .
    container_name: anaconda_project
    ports:
      - "8888:8888"          # Jupyter Labにアクセスするポート
    volumes:
      - ./notebooks:/workspace/notebooks  # Notebook共有
      - ./data:/workspace/data            # データ共有
      - ./scripts:/workspace/scripts      # スクリプト共有
      - ./results:/workspace/results      # 分析結果共有